const heroes = [
  {
    id: "1",
    name: "Iron Man",
    alias: "Tony Stark",
    image: "../../images/ironman.webp",
    universe: "Marvel",
    quotes: [
      "Genius billionaire playboy philanthropist.",
      "If you’re nothing without the suit, then you shouldn’t have it.",
      "It’s not about how much we lost, it’s about how much we have left. We’re the Avengers. We gotta finish this.",
      "Sometimes you gotta run before you can walk",
      "If we can't protect the Earth, you can be damn sure we’ll avenge it.",
      "I love you 3000.",
      "Part of the journey is the end.",
      "You can take away my house, all my tricks and toys, but one thing you can't take away—I am...",
      "We have a Hulk.",
      "I’m sorry, Earth is closed today.",
      "No amount of money ever bought a second of time.",
      "I am _______.",
    ],
    gender: "M",
    hints: [
      "Genius billionaire playboy philanthropist.",
      "Created his first suit in a cave.",
      "His AI assistant is named after a certain British butler.",
      "Started the MCU with his first solo movie in 2008.",
      "Gave Spider-Man his first real superhero suit.",
      "His final snap saved the universe.",
      "Fought alongside Captain America, but also against him.",
      "Built an army of suits but destroyed them all for love.",
      "Loves cheeseburgers.",
      "Part of the Avengers",
    ],
    splashArts: [
      "../../images/splash-arts/iron-man/iron-man-1.webp",
      "../../images/splash-arts/iron-man/iron-man-2.webp",
      "../../images/splash-arts/iron-man/iron-man-3.webp",
      "../../images/splash-arts/iron-man/iron-man-4.webp",
    ],
    emojis: ["💰", "🤖", "🔧", "🚀"],
  },

  {
    id: "2",
    name: "Spider-Man",
    alias: "Peter Parker",
    image: "../../images/spider-man.png",
    universe: "Marvel",
    quotes: [
      "With great power comes great responsibility.",
      "I’m just your friendly neighborhood _________.",
      "I’m not a hero. I’m a high school kid.",
      "That’s my job. That’s what I do. I save people.",
      "You won’t believe what I can do with a web!",
      "If you’re good at something, never do it for free.",
      "I’m gonna keep being _________, no matter what.",
      "The world’s changing, and I’m not ready yet.",
    ],
    gender: "M",
    hints: [
      "Red and blue suit.",
      "He was once bitten.",
      "One of Marvel's most famous and beloved characters.",
      "He has a famous uncle",
      "Fights crime in New York City.",
      "Founding member of the Avengers and also a high school student.",
      "His biggest strength is his agility and reflexes.",
      "He swings through the city using webs.",
      "This hero's alter ego works as a photographer.",
    ],
    splashArts: [
      "../../images/splash-arts/spider-man/spider-man-1.png",
      "../../images/splash-arts/spider-man/spider-man-2.jpg",
      "../../images/splash-arts/spider-man/spider-man-3.avif",
      "../../images/splash-arts/spider-man/spider-man-4.webp",
    ],
    emojis: ["🤓", "📸", "🕸️", "🕷️"],
  },
  {
    id: "3",
    name: "Captain America",
    alias: "Steve Rogers",
    image: "../../images/captain-america.png",
    universe: "Marvel",
    quotes: [
      "I’m just a kid from Brooklyn.",
      "The price of freedom is high, and it's a price I'm willing to pay.",
      "You get hurt, hurt 'em back. You get killed... walk it off.",
      "This isn't freedom. This is fear.",
      "Avengers, assemble!",
      "I'm loyal to that flag, but it's about time we face the fact that it's not the same flag anymore.",
      "I can do this all day.",
      "I don't want to kill anyone. I don't like bullies; I don't care where they're from.",
      "Sometimes the world needs a little bit of good, even if it’s just for a moment.",
      "I don’t need to be a perfect hero, I just need to be a better man.",
      "I’m not a hero. I’m just a man who tried to do his part.",
      "I can’t trust my own government. You expect me to trust you?",
    ],
    gender: "M",
    hints: [
      "Known for his iconic shield.",
      "Fought in World War II.",
      "Leader of the Avengers.",
      "Frozen in ice for decades before being revived.",
      "Born in Brooklyn and grew up during the Great Depression.",
      "Symbol of hope and freedom during his time in the 1940s.",
      "Fought against the villainous organization Hydra.",
      "His best friend is Bucky Barnes.",
    ],
    splashArts: [
      "../../images/splash-arts/captain-america/captain-america-1.webp",
      "../../images/splash-arts/captain-america/captain-america-2.jpg",
      "../../images/splash-arts/captain-america/captain-america-3.jpg",
      "../../images/splash-arts/captain-america/captain-america-4.jpg",
    ],
    emojis: ["🛡️", "💪", "🪖", "🇺🇲"],
  },
  {
    id: "4",
    name: "Batman",
    alias: "Bruce Wayne",
    image: "../../images/batman.webp",
    universe: "DC",
    quotes: [
      "I am vengeance. I am the night. I am ______.",
      "It's not who I am underneath, but what I do that defines me.",
      "You either die a hero, or you live long enough to see yourself become the villain.",
      "The night is darkest just before the dawn.",
      "I wear a mask. The mask is not to hide who I am, but to create what I am.",
      "I won't kill you, but I don't have to save you.",
      "Swear to me!",
      "To them, I'm the bad guy.",
      "I fight for those who can't fight for themselves.",
      "Justice is about harmony. Revenge is about making yourself feel better.",
    ],
    gender: "M",
    hints: [
      "Known for his brooding nature and obsession with justice.",
      "He fights crime in Gotham City",
      "Operates primarily at night.",
      "Inspired to become a crimefighter after witnessing the murder of his parents as a child.",
      "Has no superpowers but relies on his intellect, training, and gadgets.",
      "His main villain is the Joker.",
      "Founding member of the Justice League.",
      "The Dark Knight.",
      "Possesses an iconic vehicle equipped with advanced technology.",
    ],
    splashArts: [
      "../../images/splash-arts/batman/batman-1.webp",
      "../../images/splash-arts/batman/batman-2.webp",
      "../../images/splash-arts/batman/batman-3.jpg",
      "../../images/splash-arts/batman/batman-4.webp",
    ],
    emojis: ["🦇", "🖤", "🌙", "👤"],
  },
  {
    id: "5",
    name: "Superman",
    alias: "Clark Kent",
    image: "../../images/superman.png",
    universe: "DC",
    quotes: [
      "I'm not your enemy. I'm here to help.",
      "The world doesn't need a savior. But every day I hear people crying for one.",
      "I’m here to fight for truth and justice, and I won’t let anyone stand in the way of that.",
      "I can’t let you do that. I’m not a god. I’m just a man with a great responsibility.",
      "You don't get to decide who lives or dies!",
      "I believe in truth. But I also believe in justice.",
      "Sometimes you have to give up the things you want to protect the ones you love.",
      "I will always be there to protect the people of this planet.",
      "I believe in a world where people can be free.",
      "It’s not about who I am underneath, but what I do that defines me.",
      "It's not an easy thing to do, but I choose to be the symbol of hope for the people.",
      "I will stand by you, even when the world turns against us.",
    ],
    gender: "M",
    hints: [
      "This hero's alter ego is a mild-mannered reporter at the Daily Planet.",
      "Comes from a destroyed planet and is often referred to as the 'Man of Steel'.",
      "This superhero's powers include flight, super strength, and heat vision.",
      "Has a weakness to Kryptonite.",
      "His iconic symbol is an 'S'",
      "Can fly faster than a speeding bullet.",
      "His home planet was called Krypton, and it exploded when he was a baby.",
      "He has an iconic red cape.",
      "This hero's iconic costume was made by his adoptive mother.",
    ],
    splashArts: [
      "../../images/splash-arts/superman/superman-1.jpeg",
      "../../images/splash-arts/superman/superman-2.jpg",
      "../../images/splash-arts/superman/superman-3.webp",
      "../../images/splash-arts/superman/superman-4.webp",
    ],
    emojis: ["🦸‍♂️", "💪", "🌍", "🔥👀"],
  },
  {
    id: "6",
    name: "Wolverine",
    alias: "Logan",
    image: "../../images/wolverine.png",
    universe: "Marvel",
    quotes: [
      "Nature made me a freak. Man made me a weapon. And God made it last too long.",
      "Sometimes when you cage the beast, the beast gets angry.",
      "Pain lets you know you're still alive.",
      "If you cage the beast, the beast will get angry.",
      "You wanna know how I got these claws?",
      "Sometimes, the only way out is to go through.",
      "I'm the best there is at what I do, but what I do best isn't very nice.",
    ],
    gender: "M",
    hints: [
      "Razor-sharp claws that extend from his hands.",
      "Ability to heal from almost any injury.",
      "Heightened animal-like senses.",
      "Often says 'bub' when talking to others.",
      "Famous for his gruff attitude and short temper.",
      "Wears a yellow and black costume.",
      "Has a long rivalry with Sabretooth.",
      "Weapon X experimented on him.",
      "Born in Canada.",
    ],
    splashArts: [
      "../../images/splash-arts/wolverine/wolverine-1.avif",
      "../../images/splash-arts/wolverine/wolverine-2.webp",
      "../../images/splash-arts/wolverine/wolverine-3.jpg",
      "../../images/splash-arts/wolverine/wolverine-4.webp",
    ],
    emojis: ["🐺", "🇨🇦", "⚔️", "🔪"],
  },
  {
    id: "7",
    name: "Hulk",
    alias: "Bruce Banner",
    image: "../../images/hulk.png",
    universe: "Marvel",
    quotes: [
      "____ SMASH!",
      "Don't make me angry. You wouldn't like me when I'm angry.",
      "____ is the strongest one there is!",
      "____ will break you!",
      "____ just wants to be left alone.",
      "That's my secret, Cap. I'm always angry.",
      "Puny God!",
      "Everything’s Going To Be Alright Now. I Got This. You Want To Know Who I Am?",
      "No Banner, Only ____!",
      "Big Monster?!",
      "I’m Sorry! I Just Get So Angry All The Time. ____ Always… Always Angry.",
      "You’re ______’s friend. I’ll smash you last.",
      "____ tired of puny humans.",
    ],
    gender: "M",
    hints: [
      "Strength increases with his rage.",
      "His alter ego is a scientist.",
      "Was exposed to gamma radiation.",
      "Often struggles to control his transformations.",
      "One of the strongest beings in the Marvel Universe.",
      "Has an iconic rivalry with the military.",
      "Fought Thor in an arena battle.",
      "Turns into a giant green monster when angry.",
      "Wears ripped purple pants.",
      "His intelligence varies depending on his form.",
    ],
    splashArts: [
      "../../images/splash-arts/hulk/hulk-1.avif",
      "../../images/splash-arts/hulk/hulk-2.webp",
      "../../images/splash-arts/hulk/hulk-3.webp",
      "../../images/splash-arts/hulk/hulk-4.avif",
    ],
    emojis: ["💚", "👊", "😡", "🏋️‍♂️"],
  },
  {
    id: "8",
    name: "Wonder Woman",
    alias: "Diana Prince",
    image: "../../images/wonder-woman.png",
    universe: "DC",
    quotes: [
      "I am _____ of __________, daughter of Hippolyta, queen of the Amazons.",
      "It's not about deserve, it's about what you believe. And I believe in love.",
      "I will fight for those who cannot fight for themselves.",
      "You have been warned.",
      "The world can be a cruel place, but it's worth fighting for.",
      "I am not a god, I am a warrior.",
      "You have no idea what I’m capable of.",
      "When you have lived as long as I have, you learn that nothing is ever really lost.",
      "We don't have to do this the hard way.",
      "You are a weapon, but you are also a woman.",
      "Only love can save the world.",
    ],
    gender: "F",
    hints: [
      "Amazonian princess.",
      "Possesses superhuman strength and agility.",
      "Wields a lasso that forces people to tell the truth.",
      "Has indestructible bracelets that can deflect bullets.",
      "Her iconic weapon is a sword and shield.",
      "Her symbol is an eagle or a 'W' emblem.",
      "Her costume features a red top, blue skirt, and golden tiara.",
      "One of the most powerful female superheroes in DC.",
    ],
    splashArts: [
      "../../images/splash-arts/wonder-woman/wonder-woman-1.webp",
      "../../images/splash-arts/wonder-woman/wonder-woman-2.webp",
      "../../images/splash-arts/wonder-woman/wonder-woman-3.avif",
      "../../images/splash-arts/wonder-woman/wonder-woman-4.webp",
    ],
    emojis: ["👑", "🛡️", "🗡️", "👩"],
  },
  {
    id: "9",
    name: "Thor",
    alias: "Thor Odinson",
    image: "../../images/thor.png",
    universe: "DC",
    quotes: [
      "I am ____, son of Odin!",
      "Bring me Thanos!",
      "The sun will shine on us again.",
      "I choose to run towards my problems, and not away from them.",
      "I am the God of Thunder!",
      "You’re not the only one with a cape.",
      "For Asgard!",
      "You are unworthy of the throne!",
      "I have nothing to prove to you.",
      "The hammer is not what makes me worthy.",
      "I like this one!",
    ],
    gender: "M",
    hints: [
      "God of Thunder",
      "Son of Odin.",
      "His iconic weapon is Mjolnir, a magical hammer.",
      "He comes from Asgard.",
      "His adopted brother is Loki.",
      "Member of the Avengers.",
      "Has the ability to summon lightning.",
      "Has long blonde hair.",
      "Has an iconic helmet with wings.",
      "Has an iconic red cape.",
      "He was involved in the battle against Thanos in Avengers: Infinity War and Endgame.",
    ],
    splashArts: [
      "../../images/splash-arts/thor/thor-1.jpg",
      "../../images/splash-arts/thor/thor-2.webp",
      "../../images/splash-arts/thor/thor-3.webp",
      "../../images/splash-arts/thor/thor-4.jpg",
    ],
    emojis: ["🔨", "⚡", "🧔", "👱‍♂️"],
  },
  {
    id: "10",
    name: "Flash",
    alias: "Barry Allen",
    image: "../../images/flash.png",
    universe: "DC",
    quotes: [
      "My name is _____ _____, and I am the fastest man alive.",
      "You’re not faster than me.",
      "I’m _____, I run really fast!",
      "I’m just trying to save the world, one city at a time.",
      "Running. It's what I do.",
      "You have to trust me. I have been through so many timelines, I can’t even remember half of them.",
      "Time is a tricky thing.",
      "The fastest man alive isn’t just about speed. It’s about making a difference.",
      "I make my own fate.",
      "You can’t outrun the past.",
      "Speed is a gift, but it’s also a burden.",
    ],
    gender: "M",
    hints: [
      "Gained his powers from a lightning strike and chemicals",
      "Fastest men alive.",
      "Member of the Justice League.",
      "His symbol is a lightning bolt.",
      "He comes from Central City.",
      "He is a forensic scientist by day.",
      "Wears a red suit with yellow accents.",
      "Has a connection with time travel and alternate universes.",
      "He has a strong romantic connection with Iris West.",
    ],
    splashArts: [
      "../../images/splash-arts/flash/flash-1.jpg",
      "../../images/splash-arts/flash/flash-2.jpg",
      "../../images/splash-arts/flash/flash-3.avif",
      "../../images/splash-arts/flash/flash-4.jpeg",
    ],
    emojis: ["⚡", "🏃‍♂️", "💨", "⏱️"],
  },
  {
    id: "11",
    name: "Daredevil",
    alias: "Matt Murdock",
    image: "../../images/daredevil.png",
    universe: "Marvel",
    quotes: [
      "I’m not afraid of you. I’m afraid of what I’m capable of.",
      "I’m not seeking penance for what I’ve done, Father. I’m asking forgiveness for what I’m about to do.",
      "You can beat me, but you can’t break me.",
      "Justice is blind, and so am I.",
      "The thing about the truth is, you can run from it, you can hide from it, but it always catches up with you.",
      "I’m not your hero. I’m just a man who got a little lost.",
      "If you can’t see the truth, then you’re blind.",
      "I wear the mask because I’m afraid. Afraid of what I might do if I don’t.",
      "The only thing I need to see is the truth.",
      "I’m not a hero. I’m just a guy doing his best.",
      "You can’t take justice into your own hands... unless you’re me.",
    ],
    gender: "M",
    hints: [
      "He is a blind lawyer by day and a vigilante by night.",
      "His enhanced senses allow him to 'see' in a unique way.",
      "He fights crime in Hell's Kitchen, New York.",
      "His primary weapon is his billy club, which he uses for offense and defense.",
      "Wears a red suit.",
      "His arch-nemesis is Wilson Fisk, also known as Kingpin.",
      "He is a founding member of the superhero team, the Defenders.",
      "His father, a boxer named Jack Murdock, was murdered when he was young.",
      "He has a strong moral code and seeks justice, not revenge.",
      "He was inspired to become _________ after the tragic death of his father.",
    ],
    splashArts: [
      "../../images/splash-arts/daredevil/daredevil-1.avif",
      "../../images/splash-arts/daredevil/daredevil-2.webp",
      "../../images/splash-arts/daredevil/daredevil-3.webp",
      "../../images/splash-arts/daredevil/daredevil-4.jpg",
    ],
    emojis: ["🔴", "👨‍⚖️", "👂", "👁️"],
  },
  {
    id: "12",
    name: "Deadpool",
    alias: "Wade Wilson",
    image: "../../images/deadpool.png",
    universe: "Marvel",
    quotes: [
      "I'm not a hero. I'm a bad guy who just happens to be really good at being a hero.",
      "Maximum effort!",
      "I don't have time for your X-Men bullshit.",
      "You look like an avocado had sex with an older avocado.",
      "Life is an endless series of trainwrecks with only brief, commercial-like breaks of happiness.",
      "It's not about me. It's about you, and I love you.",
      "You might be wondering why the red suit. Well, that's so bad guys can't see me bleed.",
      "I’m just a guy who’s trying to make the world a better place by being a complete and utter pain in the ass.",
      "I’m not letting this get to me. I’m gonna keep it together. I’m gonna keep it together… Okay, I’m gonna go cry now.",
      "I can’t die. I’m like the Terminator, only better-looking.",
      "You're probably thinking, 'Did he shoot six shots, or only five?' Well, to tell you the truth, in all this excitement, I kind of lost track myself.",
      "Is this the part where I say I’m sorry for almost killing you? Nah. It’s not me.",
      "You’re like a bad fart that won’t go away.",
    ],
    gender: "M",
    hints: [
      "Known for his humor and breaking the fourth wall.",
      "His power allows him to heal rapidly from nearly any injury.",
      "Recognizable for his red costume, designed to hide his scars.",
      "Loves chimichangas.",
      "Master of hand-to-hand fighting and weaponry.",
      "Unlike traditional heroes, he’s known for his chaotic methods.",
      "His powers come from a failed experiment to cure his cancer.",
      "Often sarcastic, witty, and unapologetic in his approach.",
      "Prefers katanas and guns for his battles.",
      "His humor is often dark and over-the-top.",
      "Has a strong bond with Dopinder, a taxi driver.",
    ],
    splashArts: [
      "../../images/splash-arts/deadpool/deadpool-1.jpg",
      "../../images/splash-arts/deadpool/deadpool-2.webp",
      "../../images/splash-arts/deadpool/deadpool-3.webp",
      "../../images/splash-arts/deadpool/deadpool-4.webp",
    ],
    emojis: ["🤪", "🩸", "🥂", "🤺"],
  },
  {
    id: "13",
    name: "Black Panther",
    alias: "T'Challa",
    image: "../../images/black-panther.png",
    universe: "Marvel",
    quotes: [
      "In my culture, death is not the end. It's more of a stepping-off point.",
      "I have seen gods fly. I've seen men build weapons that I couldn't even imagine. I've seen aliens drop from the sky. But I have never seen anything like this.",
      "You get to decide what kind of king you want to be.",
      "The world is changing. Soon there will only be the conquered and the conquerors. I know what I must do.",
      "I am not ready to be without you.",
      "Wakanda will no longer watch from the shadows.",
      "I am not the king of all people. I am the king of Wakanda.",
      "A good man does what he can to protect his country. A great man does what he must.",
      "Wakanda forever!",
      "We must find a way to look after one another, as if we were one single tribe.",
      "It’s hard to be a king, but you don’t do it alone.",
    ],
    gender: "M",
    hints: [
      "King of a secretive, advanced African nation.",
      "His black suit is made from a rare, indestructible metal called Vibranium.",
      "Has enhanced strength, speed, and agility thanks to a special herb.",
      "Known for his signature catchphrase: 'Wakanda Forever!'",
      "Member of the Avengers and a leader of Wakanda.",
      "Known for being a protector of his people and his nation.",
      "First black superhero to appear in Marvel comics.",
      "His arch-nemesis is Erik Killmonger.",
    ],
    splashArts: [
      "../../images/splash-arts/black-panther/black-panther-1.webp",
      "../../images/splash-arts/black-panther/black-panther-2.jpeg",
      "../../images/splash-arts/black-panther/black-panther-3.webp",
      "../../images/splash-arts/black-panther/black-panther-4.webp",
    ],
    emojis: ["🐾", "🖤", "🇿🇦", "👑"],
  },
  {
    id: "14",
    name: "Aquaman",
    alias: "Arthur Curry",
    image: "../../images/aquaman.png",
    universe: "DC",
    quotes: [
      "My father was a lighthouse keeper. My mother was a queen. They were never supposed to meet. But their love saved the world.",
      "I am the protector of the oceans. And you will listen to me!",
      "I don't need a trident to be king.",
      "You’re not gonna make it. You’re gonna die in this ocean. And you’ll be forgotten.",
      "It’s not just a weapon, it’s a symbol.",
      "When you die, you’ll find yourself standing before the one who created everything. And you’ll say to him, 'I was your king!'",
      "I’m not a hero. I’m a god.",
      "The ocean is a dangerous place, but it's my place.",
      "I am the protector of the ocean and its creatures.",
      "The power of the ocean is in my veins.",
      "You fight the whole world for your kingdom. But all you do is hurt it.",
    ],
    gender: "M",
    hints: [
      "King of Atlantis.",
      "Half-human, half-Atlantean.",
      "Can communicate with sea creatures.",
      "Wields the powerful Trident of Poseidon.",
      "Member of the Justice League.",
      "His iconic appearance includes a green and gold costume.",
      "Possesses enhanced vision, strength, and speed",
      "Aquatic hero who protects both land and sea.",
    ],
    splashArts: [
      "../../images/splash-arts/aquaman/aquaman-1.avif",
      "../../images/splash-arts/aquaman/aquaman-2.webp",
      "../../images/splash-arts/aquaman/aquaman-3.webp",
      "../../images/splash-arts/aquaman/aquaman-4.avif",
    ],
    emojis: ["🌊", "🔱", "👑", "🐠"],
  },
  {
    id: "15",
    name: "Nightwing",
    alias: "Dick Grayson",
    image: "../../images/nightwing.png",
    universe: "DC",
    quotes: [
      "I'm not Batman. I won't be Batman. But I will always be the protector of this city.",
      "The night is my friend, my ally. And I will never stop fighting for the people of this city.",
      "I may not have the cape, but I’ll still fight like I do.",
      "I used to be Robin, but now I’m _________. And that means I fight for my own cause.",
      "I don’t need a sidekick. I need a partner.",
      "I've learned from the best. I don't need to be Batman, I just need to be me.",
      "I may not be the Dark Knight, but I’m still Gotham’s guardian.",
    ],
    gender: "M",
    hints: [
      "Former sidekick to Batman.",
      "Originally known as Robin before adopting a new identity.",
      "Leader of the Teen Titans.",
      "Known for his acrobatic skills and agility.",
      "Wields eskrits (a pair of weapons that resemble batons).",
      "Protector of Blüdhaven after leaving Gotham.",
      "Has a strong sense of justice, but works independently from Batman.",
      "Has a close relationship with Batman, but sometimes disagrees with his methods.",
      "Former circus acrobat before becoming Robin.",
      "First appeared in Detective Comics #38 (1940).",
      "Wears a blue and black costume with a bird symbol on his chest.",
      "Often seen as the 'heart' of the Batman family.",
    ],
    splashArts: [
      "../../images/splash-arts/nightwing/nightwing-1.webp",
      "../../images/splash-arts/nightwing/nightwing-2.jpg",
      "../../images/splash-arts/nightwing/nightwing-3.avif",
      "../../images/splash-arts/nightwing/nightwing-4.jpg",
    ],
    emojis: ["🦇", "💙", "🎪", "🤸‍♂️"],
  },
  {
    id: "16",
    name: "Black Widow",
    alias: "Natasha Romanoff",
    image: "../../images/black-widow.png",
    universe: "Marvel",
    quotes: [
      "I'm not the one who needs to watch their back.",
      "I’ve got red in my ledger. I’d like to wipe it out.",
      "You’re a monster. I’ve been a monster. I don’t feel sorry for you.",
      "I’ve been fighting with one arm tied behind my back. But what happens when I’m finally set free?",
      "I’m always picking up after you boys.",
      "You’re fooling yourself. We’re all gonna die, but not today.",
      "I don’t judge people on their worst mistakes.",
      "I’ve had a lot of people I’ve had to say goodbye to. So, that’s just the way it is.",
      "Even when I had nothing, I had Bucky.",
      "Pain only makes us stronger.",
      "Nothing lasts forever.",
      "At some point, we all have to choose between what the world wants you to be and who you are.",
      "Regimes fall every day. I tend not to weep over that, I’m Russian, or was.",
      "Just because it’s the path of least resistance doesn’t mean it’s the wrong path.",
    ],
    gender: "F",
    hints: [
      "Highly skilled spy and assassin.",
      "Master of disguise and deception.",
      "Her codename is inspired by a venomous spider.",
      "Expert in martial arts and hand-to-hand combat.",
      "Wears a black suit with red accents.",
      "Close ally of a skilled archer.",
      "Has a complex past tied to Russian intelligence.",
      "Trained in the Red Room program.",
      "Her body ages slower due to enhancements.",
      "Uses electric batons and stun-based weapons.",
    ],
    splashArts: [
      "../../images/splash-arts/black-widow/black-widow-1.jpg",
      "../../images/splash-arts/black-widow/black-widow-2.webp",
      "../../images/splash-arts/black-widow/black-widow-3.webp",
      "../../images/splash-arts/black-widow/black-widow-4.webp",
    ],
    emojis: ["🕷️", "💃", "🥷", "🔴⚫"],
  },
  {
    id: "17",
    name: "Green Lantern",
    alias: "Hal Jordan",
    image: "../../images/green-lantern.png",
    universe: "DC",
    quotes: [
      "In brightest day, in blackest night, No evil shall escape my sight. Let those who worship evil’s might,Beware my power",
      "No matter how bad things get, something good is out there, just over the horizon.",
      "The ring didn’t see that you were fearless. It saw that you had the ability to overcome fear.",
      "We’re the _____ _______ Corps, we eat threats like this for breakfast!",
      "We walk in the dark places no others will enter. We stand on the bridge and no one may pass. We live for the One, we die for the One.",
      "You’re telling me the ring chose you? There must have been a shortage of candidates.",
      "The ring didn’t make me a hero. I already was one.",
      "Being a _______ isn’t about power. It’s about will. And nobody has stronger will than me.",
      "Batman… what, no superpowers? I feel naked.",
      "The ring saw something in me. Something I don’t even see in myself.",
    ],
    gender: "M",
    hints: [
      "Member of an intergalactic police force.",
      "Wields a ring that channels green energy, powered by willpower.",
      "Known for reciting an oath to harness the power of his ring.",
      "Often fights against fear-based villains, including Sinestro.",
      "Former test pilot.",
      "He is assigned to protect Sector 2814, which includes Earth.",
      "Has made numerous self-sacrifices, often risking his life for the greater good of the universe.",
      "His ring can create constructs and fly.",
    ],
    splashArts: [
      "../../images/splash-arts/green-lantern/green-lantern-1.jpg",
      "../../images/splash-arts/green-lantern/green-lantern-2.webp",
      "../../images/splash-arts/green-lantern/green-lantern-3.webp",
      "../../images/splash-arts/green-lantern/green-lantern-4.webp",
    ],
    emojis: ["🟩", "💍", "🛸", "🌌"],
  },
  {
    id: "18",
    name: "Jean Grey",
    alias: "Phoenix",
    image: "../../images/jean-grey.png",
    universe: "Marvel",
    quotes: [
      "This is what I am now. It's who I am. I'm not going to hide from it.",
      "I have to be able to control my powers, but how can I control them if I don't know what they are?",
      "What if I can't control it? What if it controls me?",
      "I don't know how to live with this power, but I have to.",
      "The _______ is not the enemy. It’s me.",
      "You’re right. I’m not the woman you think I am. I’m much more than that.",
      "You don’t deserve this. No one does.",
      "I am not afraid of what I am. I’m afraid of what I can become.",
    ],
    gender: "F",
    hints: [
      "She is one of the founding members of the X-Men.",
      "Has telepathic and telekinetic abilities.",
      "Her powers manifested at a young age, and she was later recruited by Professor Charles Xavier to join the X-Men.",
      "She has a long-term relationship with Cyclops (Scott Summers), and is also a key figure in the love triangle involving Wolverine.",
      "Known for her emotional struggles with her powers and the _______ Force",
      "Developed her powers as a child when she witnessed the death of her best friend, causing her telepathic abilities to emerge.",
      "She is possessed by the _______ Force, which grants her god-like powers, including control over life and death.",
      "Has died and returned multiple times, with her death and resurrection being key parts of her story.",
      "She is a close friend of Professor X and has a special bond with her fellow X-Men.",
    ],
    splashArts: [
      "../../images/splash-arts/jean-grey/jean-grey-1.avif",
      "../../images/splash-arts/jean-grey/jean-grey-2.webp",
      "../../images/splash-arts/jean-grey/jean-grey-3.jpg",
      "../../images/splash-arts/jean-grey/jean-grey-4.jpg",
    ],
    emojis: ["🐦‍🔥", "🧠", "👩‍🦰", "🔥"],
  },
  {
    id: "19",
    name: "Cyclops",
    alias: "Scott Summers",
    image: "../../images/cyclops.webp",
    universe: "Marvel",
    quotes: [
      "You don’t know what I’ve been through.",
      "I can’t control it! I need you to help me!",
      "I have to stop you, Jean. I love you, but I have to stop you.",
      "Jean, you’re not yourself. This isn’t you!",
      "The X-Men are a family. We take care of each other.",
      "We’re not just mutants. We’re human beings too.",
      "I’m not afraid of what you’ll do to me, I’m afraid of what I’ll do to you.",
      "Jean, no matter what happens, you are always my home.",
      "The cost of leadership is high, but it’s the price I’m willing to pay.",
      "I’m not a fighter, I’m a leader.",
    ],
    gender: "M",
    hints: [
      "Known for his powerful optic blasts, which he can’t control without his visor or glasses.",
      "Lover of Jean Grey and often caught in love triangle dramas, especially with Wolverine.",
      "One of the oldest X-Men members, often seen as a mentor to younger mutants.",
      "Leader of the X-Men and a founding member of the team.",
      "Frequently at odds with Professor X over the best way to lead the X-Men.",
      "His optical blasts are a result of a mutation and can be incredibly destructive.",
      "His brother is Alex _______ (Havok), who has similar mutant powers.",
      "He has led the X-Men in some of their most crucial missions and battles, including against Magneto and the Sentinels.",
    ],
    splashArts: [
      "../../images/splash-arts/cyclops/cyclops-1.jpg",
      "../../images/splash-arts/cyclops/cyclops-2.webp",
      "../../images/splash-arts/cyclops/cyclops-3.webp",
      "../../images/splash-arts/cyclops/cyclops-4.jpg",
    ],
    emojis: ["👓", "💥", "💑", "🧠🌀"],
  },
  {
    id: "20",
    name: "Mister Fantastic",
    alias: "Reed Richards",
    image: "../../images/mister-fantastic.webp",
    universe: "Marvel",
    quotes: [
      "We can't always be what we want to be. We have to be what the world needs us to be.",
      "I think we can both agree... I’m the smart one.",
      "I never claimed to have all the answers, but I’ll always fight to find them.",
      "Knowledge is power, and with that power comes great responsibility.",
      "If we can solve the problem, we’ll do it. If not, we’ll try again.",
      "The greater the mind, the greater the burden.",
      "I'm not a god. I'm a scientist. But sometimes, that's the same thing.",
      "You have no idea how long I’ve waited for this. A chance to prove that I can help save the world.",
    ],
    gender: "M",
    hints: [
      "Leader of the Fantastic Four.",
      "Known for his genius-level intellect and scientific inventions.",
      "Has the ability to stretch his body.",
      "Brilliant scientist and inventor with a mind often considered one of the greatest in the Marvel Universe.",
      "Known for his strategic mind, often coming up with clever solutions in battles.",
      "Father of two children, Franklin and Valeria Richards.",
      "His iconic costume is blue with a large '4' symbol on the chest.",
      "Has fought against villains like Doctor Doom, Galactus, and Annihilus.",
      "His greatest weakness is sometimes his obsession with knowledge, which can lead to dangerous consequences.",
    ],
    splashArts: [
      "../../images/splash-arts/mister-fantastic/mister-fantastic-1.jpg",
      "../../images/splash-arts/mister-fantastic/mister-fantastic-2.jpg",
      "../../images/splash-arts/mister-fantastic/mister-fantastic-3.webp",
      "../../images/splash-arts/mister-fantastic/mister-fantastic-4.jpg",
    ],
    emojis: ["🧠", "🤸‍♂️", "🔬", "💡"],
  },
  {
    id: "21",
    name: "Punisher",
    alias: "Frank Castle",
    image: "../../images/punisher.png",
    universe: "Marvel",
    quotes: [
      "You can't take my soul.",
      "I’m the ________, and you’re dead.",
      "You can run, but you can’t hide. Not from me.",
      "This isn't vengeance. It's punishment.",
      "The law is a joke. And I’m the punchline.",
      "I’m going to make you pay for what you’ve done.",
      "The world’s full of people who think they’re untouchable. I’m here to remind them they’re not.",
      "You don't get it, do you? I don't fight for justice. I fight for vengeance.",
      "I don’t need a badge to be a hero. Just a gun.",
      "No more hesitation. No more guilt. The time for mercy has passed.",
      "You're going to die. It's just a matter of when.",
      "I don't need a reason. I just need a target.",
      "I’m not interested in your excuses. I’m interested in your death.",
    ],
    gender: "M",
    hints: [
      "A former Marine, became ________ after his family was killed by the mob.",
      "He relies on military training, weapons, and his intense combat skills, no superpowers.",
      "Known for his ruthless methods and belief in _________ criminals, not just capturing them.",
      "Often seen as an anti-hero.",
      "He operates outside the law, often going against traditional superhero norms.",
      "His main enemies include mobsters, corrupt cops, and Doctor Doom.",
      "Has a military background, which influences his tactics and arsenal.",
      "His first appearance was in The Amazing Spider-Man #129 (1974).",
      "He is known for operating solo, without a superhero team, often working alone.",
    ],
    splashArts: [
      "../../images/splash-arts/punisher/punisher-1.webp",
      "../../images/splash-arts/punisher/punisher-2.avif",
      "../../images/splash-arts/punisher/punisher-3.avif",
      "../../images/splash-arts/punisher/punisher-4.webp",
    ],
    emojis: ["💀", "🖤", "🔫", "👊"],
  },
  {
    id: "22",
    name: "Storm",
    alias: "Ororo Munroe",
    image: "../../images/storm.png",
    universe: "Marvel",
    quotes: [
      "You know what happens to a toad when it’s struck by lightning? The same thing that happens to everything else.",
      "I am a queen. I am a goddess. I am a _____.",
      "We are the future, Charles, not them. They no longer matter.",
      "I was a thief. I survived by stealing. And I thought I could never be part of something greater. But now I know I was wrong.",
      "You are all my children. And I will make you grow.",
      "I will not be broken, for I am a daughter of the wind and the _____.",
      "I am not the woman I was. I have been tested and shaped by every battle I have faced.",
      "I am a force of nature. And nature always wins.",
      "I am a queen. And I will not be treated like a beggar.",
      "I can’t change the weather, but I can change how I face it.",
      "I have been a goddess, a thief, a queen, and a leader. But I have never stopped being who I am.",
    ],
    gender: "F",
    hints: [
      "She has served as a key member and leader of the X-Men.",
      "She can control the weather, including lightning, wind, and storms.",
      "Descended from a long line of African royalty.",
      "Often seen with white hair and a costume that incorporates elements of a queen or goddess.",
      "Known for her immense strength and combat skills, she’s one of the most powerful mutants in the Marvel Universe.",
      "Her commitment to fighting for peace between mutants and humans defines her character.",
      "She has had a significant relationship with T'Challa, the Black Panther.",
      "She was born with mutant abilities, which were triggered during her childhood in Egypt.",
      "She became an orphan at a young age when her parents were killed in a plane crash that destroyed their home.",
    ],
    splashArts: [
      "../../images/splash-arts/storm/storm-1.webp",
      "../../images/splash-arts/storm/storm-2.jpg",
      "../../images/splash-arts/storm/storm-3.avif",
      "../../images/splash-arts/storm/storm-4.avif",
    ],
    emojis: ["👸🏽", "🌪️", "⚡", "🌍"],
  },
  {
    id: "23",
    name: "Thing",
    alias: "Ben Grimm",
    image: "../../images/thing.png",
    universe: "Marvel",
    quotes: [
      "It's clobberin' time!",
      "You think this is the first time I've been to space?",
      "The truth is, I've always been a freak. I just never had to deal with it.",
      "I'm not a superhero. I just got a lot of muscle and a lot of rage.",
      "You don't know what it's like... I used to be a man. Now I’m a monster.",
      "Y'know, I might be a monster, but I got more heart than you do.",
      "I may not be able to change back, but I’m still _____!",
      "What’s the deal? We’re superheroes now?",
      "This is a one-time thing. Next time, we’ll be back to clobberin’.",
      "You ever heard the saying, ‘the bigger they are, the harder they fall’?",
      "You don’t gotta worry about me. I’m tough!",
      "When you’re as tough as me, you gotta be tough on the inside too.",
    ],
    gender: "M",
    hints: [
      "A test pilot who turned into a super-strong hero after exposure to cosmic rays.",
      "One of the original members of the Fantastic Four team.",
      "Known for his incredible strength and invulnerability.",
      "Often struggles with his monstrous appearance and the loss of his human form.",
      "A deeply loyal and protective friend, especially to Reed Richards (Mr. Fantastic) and the rest of his team.",
      "Despite his powers, he occasionally deals with self-doubt due to his physical appearance.",
      "He has a romantic relationship with Alicia Masters, a blind sculptor.",
      "He has battled several notable villains, including Galactus, Dr. Doom, and The Skrulls.",
      "Although he looks intimidating, has a big heart and fights for the greater good.",
    ],
    splashArts: [
      "../../images/splash-arts/thing/thing-1.webp",
      "../../images/splash-arts/thing/thing-2.avif",
      "../../images/splash-arts/thing/thing-3.jpg",
      "../../images/splash-arts/thing/thing-4.webp",
    ],
    emojis: ["🪨", "💪", "🤜", "💥"],
  },
  {
    id: "24",
    name: "Doctor Strange",
    alias: "Stephen Strange",
    image: "../../images/doctor-strange.webp",
    universe: "Marvel",
    quotes: [
      "Dormammu, I’ve come to bargain.",
      "We never lose our demons, Mordo. We only learn to live above them.",
      "Forget everything that you think you know.",
      "I swore an oath to do no harm, and I have just killed a man. I’m not doing that again.",
      "We’re in the endgame now.",
      "You are just another tiny, momentary speck within an indifferent universe.",
      "The greatest gift we can receive is to have the chance, just once in our lives, to make a difference.",
      "I went forward in time to view alternate futures. To see all the possible outcomes of the coming conflict.",
      "I’ve spent so many years peering through time, looking at this exact moment.",
      "The multiverse is a concept about which we know frighteningly little.",
      "I protect your reality, douchebag.",
      "Not everything does. Not everything has to. That’s the thing about the multiverse.",
      "I don't need a third eye to see the truth.",
    ],
    gender: "M",
    hints: [
      "A powerful sorcerer and former neurosurgeon.",
      "Master of the Mystic Arts.",
      "Wields the Book of Vishanti.",
      "Uses the Eye of Agamotto to manipulate time.",
      "Known for his iconic red cape and the Seal of the Vishanti on his chest.",
      "Lives in the Sanctum Sanctorum.",
      "Can open portals with his Sling Ring.",
      "Trained by the Ancient One.",
      "Defender of the multiverse.",
      "Helped Spider-Man erase people's memories.",
      "Knows millions of possible futures.",
      "Fought Dormammu in a time loop.",
    ],
    splashArts: [
      "../../images/splash-arts/doctor-strange/doctor-strange-1.webp",
      "../../images/splash-arts/doctor-strange/doctor-strange-2.webp",
      "../../images/splash-arts/doctor-strange/doctor-strange-3.webp",
      "../../images/splash-arts/doctor-strange/doctor-strange-4.jpg",
    ],
    emojis: ["🧙‍♂️", "🌀", "⏳", "👁️"],
  },
  {
    id: "25",
    name: "Luke Cage",
    alias: "Power Man",
    image: "../../images/luke-cage.webp",
    universe: "Marvel",
    quotes: [
      "Sweet Christmas!",
      "You can't burn me, you can't blast me, and you definitely can't break me.",
      "Harlem’s mine. I’m not running from it.",
      "You want Harlem? You gotta go through me.",
      "A bulletproof man in a hoodie is a powerful statement.",
      "I ain’t no hero. I’m just a man that got tired of running.",
      "You keep coming at me, but I ain’t breaking.",
      "I don’t need a gun. I am the gun.",
      "Sometimes, the best way to solve your problems is to punch them in the face.",
      "I don’t need no mask. I got nothing to hide.",
    ],
    gender: "M",
    hints: [
      "Super-strong and bulletproof.",
      "Protector of Harlem.",
      "Gained powers from a prison experiment.",
      "Best friends with Iron Fist.",
      "Started as a Hero for Hire.",
      "Has a daughter with Jessica Jones.",
      "Falsely imprisoned before becoming a hero.",
      "Prefers fists over weapons.",
      "Grew up in Harlem, New York.",
      "Known for his catchphrase 'Sweet Christmas!'.",
    ],
    splashArts: [
      "../../images/splash-arts/luke-cage/luke-cage-1.webp",
      "../../images/splash-arts/luke-cage/luke-cage-2.webp",
      "../../images/splash-arts/luke-cage/luke-cage-3.avif",
      "../../images/splash-arts/luke-cage/luke-cage-4.jpg",
    ],
    emojis: ["🛡️🔫", "🦾", "🔗🚔", "👨🏿"],
  },
];

module.exports = { heroes };
